[package]
name = "scale"
version = "0.1.0"
authors = ["stephaneworkspace"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
